### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by jgabriel98** [MrLoLf/HoneygainAutoClaim#7]
I just followed the README.md instructions as below:
```bash
git clone https://github.com/MrLoLf/HoneygainAutoClaim.git
cd HoneygainAutoClaim
python3 -m pip install -r requirements.txt
cd ~
python3 /home/pi/HoneygainAutoClaim/main.py
```

But got this error on the last command:
```bash
pi@raspberrypi:~ $ python3 /home/pi/HoneygainAutoClaim/main.py
Traceback (most recent call last):
  File "/home/pi/HoneygainAutoClaim/main.py", line 17, in <module>
    header: dict[str | str] = {'Authorization': ''}
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```

It seems to be some python version problem? anyway, my python version is:
```bash
pi@raspberrypi:~ $ python --version
Python 3.9.2
```

**Comment by jgabriel98** [comment]
Uppon some reasearch, it seems the the `|` operator is a union operator (introduced at [PEP 604](https://peps.python.org/pep-0604/)).

So when you code does `header: dict[str | str] = {'Authorization': ''}` it is saying:
 _"dict, which its **type hint** is a str OR a str"_
 
Focus on **type hint** --> probably that is why the code doesn´t crash even when the type specification doesn't match the true value type.

Maybe you were meaning:
```python3
header: dict[str, str] = {'Authorization': ''}
# instead of
# header: dict[str | str] = {'Authorization': ''}
```
?

**Comment by MrLoLf** [comment]
Thanks for reporting this! It should be fixed now. I hope it will work now on your side too.

**Comment by jgabriel98** [comment]
You forgot line 152 haha:
from `def gen_token(s: requests.session, invalid: bool = False) -> str | None:`
to `def gen_token(s: requests.session, invalid: bool = False) -> str:`

Remember the real problem is **the new operator beeing supported only for python 3.10 and above**.
So only changing the occurrences on dicts types wont be enough. It is necessary to remove all ocurrences of this operator\*.

###### \*: if you wish to support all python 3 version instead of only +`3.10`

**Comment by MrLoLf** [comment]
This is supposed to be there, as this function can return booth depending on the success of the method.
```python
if "title" in token:
                print("Wrong Login Credentials. Please enter the right ones.")
                logging.error("Wrong Login Credentials. Please enter the right ones.")
                return None
```
and later has 
```python
return token["data"]["access_token"]
```

**Comment by jgabriel98** [comment]
From my understanding, `None` is like `null` on python, so any object can be `None` with no problems.
That is why the `|` is only a type hint operator and it doesn´t affect the code workflow/logic. But it does affect the python parser (that is why it breaks when < `3.10`).

My advice would be to not use this operator yet since would limit how many users could use your repo.
BUT it is your code and your decision on which base of users you want to support.

And, obviously, i can just edit the code locally on my machine to work on previous pythons (note: i did and it works 🚀 ).

------------------------

Anyway, which ever path you chose i still appreciate your efforts on providing this code! thanks!

**Comment by MrLoLf** [comment]
Nice to see it working, but I want to use this type hints, to easier see what types I get in return of the functions.
